export default function PerformanceForm(props) {
  return (
    <form onSubmit={props.handleFormSubmit}>
      <table>
        <thead>
          <tr>
            <th>
              <label htmlFor="dateInput">
                DATE
              </label>
            </th>
            <th>
              <label htmlFor="fgaInput">
                FGA
              </label>
            </th>
            <th>
              <label htmlFor="fgmInput">
                FGM
              </label>
            </th>
            <th>
              <label htmlFor="3PAInput">
                3PA
              </label>
            </th>
            <th>
              <label htmlFor="3PMInput">
                3PM
              </label>
            </th>
            <th>
              <label htmlFor="ftaInput">
                FTA
              </label>
            </th>
            <th>
              <label htmlFor="ftmInput">
                FTM
              </label>
            </th>
            <th>
              <label htmlFor="offRebInput">
                OREB
              </label>
            </th>
            <th>
              <label htmlFor="totRebsInput">
                TREB
              </label>
            </th>
            <th>
              <label htmlFor="astInput">
                AST
              </label>
            </th>
            <th>
              <label htmlFor="stlInput">
                STL
              </label>
            </th>
            <th>
              <label htmlFor="blkInput">
                BLK
              </label>
            </th>
            <th>
              <label htmlFor="turnoversInput">
                TO
              </label>
            </th>
            <th>
              <label htmlFor="pointsInput">
                PTS
              </label>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <input
                id="dateInput"
                type="date"
                name="date"
                onChange={props.handleInputChange}
                value={props.formState.date}
              />
            </td>
            <td>
              <input
                id="fgaInput"
                type="number"
                name="fgAtt"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.fgAtt}
              />
            </td>
            <td>
              <input
                id="fgmInput"
                type="number"
                name="fgMade"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.fgMade}
              />
            </td>
            <td>
              <input
                id="3PAInput"
                type="number"
                name="threePtAtt"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.threePtAtt}
              />
            </td>
            <td>
              <input
                id="3PMInput"
                type="number"
                name="threePtMade"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.threePtMade}
              />
            </td>
            <td>
              <input
                id="ftaInput"
                type="number"
                name="ftAtt"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.ftAtt}
              />
            </td>
            <td>
              <input
                id="ftmInput"
                type="number"
                name="ftMade"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.ftMade}
              />
            </td>
            <td>
              <input
                id="offRebInput"
                type="number"
                name="offReb"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.offReb}
              />
            </td>
            <td>
              <input
                id="totRebsInput"
                type="number"
                name="rebounds"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.rebounds}
              />
            </td>
            <td>
              <input
                id="astInput"
                type="number"
                name="assists"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.assists}
              />
            </td>
            <td>
              <input
                id="stlInput"
                type="number"
                name="steals"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.steals}
              />
            </td>
            <td>
              <input
                id="blkInput"
                type="number"
                name="blocks"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.blocks}
              />
            </td>
            <td>
              <input
                id="turnoversInput"
                type="number"
                name="turnovers"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.turnovers}
              />
            </td>
            <td>
              <input
                id="pointsInput"
                type="number"
                name="points"
                min="0"
                onChange={props.handleInputChange}
                value={props.formState.points}
              />
            </td>
          </tr>
        </tbody>
      </table>
      <button type="submit" id="submitNewPerformanceBtn">Add Game</button>
    </form>
  );
}